name: pushing to ACR
on:
    push:
        branches:
            - main
    workflow_dispatch:
       inputs:
            description: 'pls enter the branch name.'
            default: main
            required: true
jobs:
    BuildJob:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v3
            - name: setup the environment
              uses: actions/setup-node@v3
              with:
                    node-version: 17
            - name: install dependencies
              run: npm ci
    
     
          