name: pushing to ACR
on:
    push:
        branches:
            - main
    workflow_dispatch:
         inputs:
           customBranch:
              description: "pls  enter the branch name."
              default: main
              required: true
jobs:
    BuildJob:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v3
            - name: setup the environment
              uses: actions/setup-node@v3
              with:
                    node-version: 17
            - name: install dependencies
              run: npm ci
    Login:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v3
            - name: setup the environment
              uses: actions/setup-node@v3
              with:
                    node-version: 17
            - name: list commands
              run: ls
            - name: Azure Login
              uses: azure/login@v1
              with:
                    creds: ${{  secrets.AZURE_LOGIN  }}     
          